# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: data_service.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.api import annotations_pb2 as google_dot_api_dot_annotations__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x12\x64\x61ta_service.proto\x12\x02pb\x1a\x1cgoogle/api/annotations.proto\"*\n\x0eStudentDetails\x12\n\n\x02id\x18\x01 \x01(\x05\x12\x0c\n\x04name\x18\x02 \x01(\t\"6\n\x0bStudentData\x12\n\n\x02id\x18\x01 \x01(\x05\x12\x0c\n\x04name\x18\x02 \x01(\t\x12\r\n\x05marks\x18\x03 \x01(\x05\x32\\\n\x0b\x44\x61taService\x12M\n\x0eGetStudentData\x12\x12.pb.StudentDetails\x1a\x0f.pb.StudentData\"\x16\x82\xd3\xe4\x93\x02\x10\"\x0b/v1/student:\x01*B\x08Z\x06/pb;pbb\x06proto3')



_STUDENTDETAILS = DESCRIPTOR.message_types_by_name['StudentDetails']
_STUDENTDATA = DESCRIPTOR.message_types_by_name['StudentData']
StudentDetails = _reflection.GeneratedProtocolMessageType('StudentDetails', (_message.Message,), {
  'DESCRIPTOR' : _STUDENTDETAILS,
  '__module__' : 'data_service_pb2'
  # @@protoc_insertion_point(class_scope:pb.StudentDetails)
  })
_sym_db.RegisterMessage(StudentDetails)

StudentData = _reflection.GeneratedProtocolMessageType('StudentData', (_message.Message,), {
  'DESCRIPTOR' : _STUDENTDATA,
  '__module__' : 'data_service_pb2'
  # @@protoc_insertion_point(class_scope:pb.StudentData)
  })
_sym_db.RegisterMessage(StudentData)

_DATASERVICE = DESCRIPTOR.services_by_name['DataService']
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'Z\006/pb;pb'
  _DATASERVICE.methods_by_name['GetStudentData']._options = None
  _DATASERVICE.methods_by_name['GetStudentData']._serialized_options = b'\202\323\344\223\002\020\"\013/v1/student:\001*'
  _STUDENTDETAILS._serialized_start=56
  _STUDENTDETAILS._serialized_end=98
  _STUDENTDATA._serialized_start=100
  _STUDENTDATA._serialized_end=154
  _DATASERVICE._serialized_start=156
  _DATASERVICE._serialized_end=248
# @@protoc_insertion_point(module_scope)
